- hosts: localhost
  tasks:
    - ansible.builtin.import_tasks: tasks/ssh.yaml
    - ansible.builtin.import_tasks: tasks/core.yaml
    - ansible.builtin.import_tasks: tasks/dotfiles.yaml
    - ansible.builtin.import_tasks: tasks/zsh.yaml
    - ansible.builtin.import_tasks: tasks/neovim.yaml
    - ansible.builtin.import_tasks: tasks/brave.yaml
    - ansible.builtin.import_tasks: tasks/python.yaml
    - ansible.builtin.import_tasks: tasks/rust.yaml
    - ansible.builtin.import_tasks: tasks/alacritty.yaml
    - ansible.builtin.import_tasks: tasks/i3.yaml
