- name: Install Alacritty prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - pkg-config
      - python3
  tags:
    - alacritty
- name: Install Alacritty
  ansible.builtin.shell: "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo install alacritty"
  tags:
    - alacritty
