- name: Install Alacritty
  become: true
  ansible.builtin.apt:
    name: alacritty
  tags:
    - alacritty
- name: Install picom
  become: true
  ansible.builtin.apt:
    name: picom
  tags:
    - alacritty
