- name: Download Brave GPG key
  become: true
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags:
    - brave
- name: Set up Brave repository
  become: true
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - brave
- name: Install Brave
  become: true
  ansible.builtin.apt:
    name: brave-browser
    update_cache: yes
  tags:
    - brave
