- name: Download Brave GPG key
  become: true
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags:
    - brave
- name: Add Brave repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    filename: brave-browser-release
  tags:
    - brave
- name: Install Brave
  become: true
  ansible.builtin.apt:
    name: brave-browser
    update_cache: yes
  tags:
    - brave
