- name: Upgrade packages and update repositories cache
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  tags:
    - always
- name: Install core system packages
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - git
  tags:
    - always
