- name: Install stow
  become: true
  ansible.builtin.apt:
    name: stow
  tags:
    - dotfiles
- name: Clone dotfiles
  ansible.builtin.git:
    repo: git@github.com:Przemoo16/.dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: true
  tags:
    - dotfiles
- name: Stow dotfiles
  ansible.builtin.shell: ./install
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
  tags:
    - dotfiles
