- name: Install i3
  become: true
  ansible.builtin.apt:
    name: i3
  tags:
    - i3
- name: Install i3 related packages
  become: true
  ansible.builtin.apt:
    name:
      - autorandr
      - brightnessctl
      - feh
      - lightdm
      - maim
  tags:
    - i3
