- name: Install Neovim prerequisites
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - curl
      - gettext
      - ninja-build
      - unzip
  tags:
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim
- name: Build Neovim
  ansible.builtin.shell: make CMAKE_BUILD_TYPE=Release
  args:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim
- name: Install Neovim
  become: true
  ansible.builtin.shell: make install
  args:
    chdir: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim
