- name: Install nvm
  ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm"
  tags:
    - node
- name: Install LTS version of Node.js
  ansible.builtin.shell: source "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh" && nvm install --lts
  args:
    executable: /usr/bin/env bash
  tags:
    - node
