- name: Install uv
  ansible.builtin.shell: curl -LsSf https://astral.sh/uv/install.sh | env INSTALLER_NO_MODIFY_PATH=1 sh
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/uv"
  tags:
    - python
