- name: Ensure .ssh directory exists
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install personal SSH private key
  ansible.builtin.copy:
    src: "./ssh/personal"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/personal"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Install personal SSH public key
  ansible.builtin.copy:
    src: "./ssh/personal.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/personal.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh
- name: Install Squirro SSH private key
  ansible.builtin.copy:
    src: "./ssh/squirro"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/squirro"
    mode: 0600
  tags:
    - ssh
- name: Install Squirro SSH public key
  ansible.builtin.copy:
    src: "./ssh/squirro.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/squirro.pub"
    mode: 0644
  tags:
    - ssh
- name: Set authorized keys
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tags:
    - dotfiles
    - ssh
- name: Copy SSH config
  ansible.builtin.copy:
    src: "./ssh/config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    mode: 0600
  tags:
    - dotfiles
    - ssh
