- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
  tags:
    - zsh
- name: Make zsh the default shell
  become: true
  ansible.builtin.shell: chsh -s $(which zsh)
  tags:
    - zsh
- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
  args:
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  tags:
    - zsh
- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1
  tags:
    - zsh
