- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
  tags:
    - zsh
- name: Make zsh the default shell
  become: true
  ansible.builtin.shell: chsh -s $(which zsh)
  tags:
    - zsh
- name: Check if Oh My Zsh is already installed
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh_stats
  tags:
    - zsh
- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not oh_my_zsh_stats.stat.exists
  tags:
    - zsh
- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags:
    - zsh
